apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: samplecontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: {}
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
